const fontFamilyList = [
  'Vollkorn',
  'PressStart2P',
  'Lobster',
  'Pacifico',
  'Caveat',
  'AmaticSC',
  'DotGothic16',
  'Oswald',
  'PTMono',
  'YesevaOne',
  'OrelegaOne',
  // 'Alegreya',
  // 'B612',
  // 'TitilliumWeb',
  // 'Varela',
  // 'Rakkas',
  // 'ConcertOne',
  // 'YatraOne',
  // 'OldStandardTT',
  // 'Neonderthaw',
  // 'DancingScript',
  // 'SedgwickAve',
  // 'IndieFlower',
  // 'Sacramento',
  // 'FrederickatheGreat',
  // 'ReenieBeanie',
  // 'BungeeShade',
  // 'UnifrakturMaguntia'
];
